@echo off
echo ========================================
echo Verifying Authentication Setup
echo ========================================
echo.

node -e "const db = require('./config/database'); (async () => { try { const connection = await db.getPool().getConnection(); console.log('Checking organizations table...'); const [orgTable] = await connection.execute(`SHOW TABLES LIKE 'organizations'`); if (orgTable.length > 0) { console.log('✅ organizations table exists'); const [orgCount] = await connection.execute(`SELECT COUNT(*) as count FROM organizations`); console.log(`   Found ${orgCount[0].count} organizations`); } else { console.log('❌ organizations table NOT found'); } console.log(''); console.log('Checking users table...'); const [userTable] = await connection.execute(`SHOW TABLES LIKE 'users'`); if (userTable.length > 0) { console.log('✅ users table exists'); const [userCount] = await connection.execute(`SELECT COUNT(*) as count FROM users`); console.log(`   Found ${userCount[0].count} users`); } else { console.log('❌ users table NOT found'); } console.log(''); console.log('Checking stix_reports columns...'); const [orgCol] = await connection.execute(`SHOW COLUMNS FROM stix_reports LIKE 'organization_id'`); if (orgCol.length > 0) { console.log('✅ organization_id column exists in stix_reports'); } else { console.log('❌ organization_id column NOT found in stix_reports'); } const [userCol] = await connection.execute(`SHOW COLUMNS FROM stix_reports LIKE 'user_id'`); if (userCol.length > 0) { console.log('✅ user_id column exists in stix_reports'); } else { console.log('❌ user_id column NOT found in stix_reports'); } console.log(''); console.log('Checking system organization...'); const [sysOrg] = await connection.execute(`SELECT * FROM organizations WHERE id = 'system-legacy'`); if (sysOrg.length > 0) { console.log('✅ System organization exists'); console.log(`   Name: ${sysOrg[0].org_name}`); } else { console.log('❌ System organization NOT found'); } console.log(''); console.log('Checking legacy reports...'); const [legacyReports] = await connection.execute(`SELECT COUNT(*) as count FROM stix_reports WHERE organization_id = 'system-legacy'`); console.log(`✅ ${legacyReports[0].count} reports assigned to System organization`); console.log(''); console.log('========================================'); console.log('Verification Complete!'); console.log('========================================'); connection.release(); process.exit(0); } catch (error) { console.error('❌ Error:', error.message); process.exit(1); } })();"

echo.
pause
